/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./*.html",
    "./about/**/*.html",
    "./blog/**/*.html",
    "./case-studies/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        // Core brand tokens
        "accent-performance": "#E63946",
        "surface-primary": "#0D0D0D",
        "surface-secondary": "#262626",
        "on-surface-warm": "#F9F9F7",
        "muted-silver": "#A3A3A3",
        // Extended material tokens (used across pages)
        "secondary-fixed": "#e3e2e2",
        "inverse-on-surface": "#313030",
        "primary-fixed": "#ffdad8",
        "on-secondary-container": "#b8b8b8",
        "secondary": "#c7c6c6",
        "inverse-primary": "#bb152c",
        "on-error": "#690005",
        "secondary-container": "#484949",
        "error-container": "#93000a",
        "surface-container-low": "#1c1b1b",
        "surface-tint": "#ffb3b1",
        "on-secondary": "#2f3131",
        "surface-variant": "#353534",
        "secondary-fixed-dim": "#c7c6c6",
        "surface-bright": "#3a3939",
        "on-secondary-fixed-variant": "#464747",
        "outline-variant": "#5b403f",
        "on-background": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary": "#680011",
        "primary-container": "#ff535b",
        "background": "#131313",
        "on-tertiary": "#003733",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#6fd8cc",
        "on-tertiary-fixed": "#00201d",
        "surface": "#131313",
        "surface-dim": "#131313",
        "outline": "#ab8987",
        "tertiary": "#6fd8cc",
        "on-tertiary-container": "#00302c",
        "primary-fixed-dim": "#ffb3b1",
        "on-surface": "#e5e2e1",
        "on-primary-fixed-variant": "#92001c",
        "surface-container-highest": "#353534",
        "tertiary-fixed": "#8cf4e8",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#e4bebc",
        "on-primary-fixed": "#410007",
        "on-tertiary-fixed-variant": "#00504a",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "surface-container": "#201f1f",
        "on-primary-container": "#5b000e",
        "primary": "#ffb3b1",
        "tertiary-container": "#2fa096",
      },
      borderRadius: {
        DEFAULT: "0rem",
        lg: "0rem",
        xl: "0rem",
        full: "0rem",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "64px",
        unit: "8px",
        "margin-mobile": "20px",
        "margin-tablet": "32px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "display-xl-mobile": ["Hanken Grotesk", "sans-serif"],
        "display-xl": ["Hanken Grotesk", "sans-serif"],
        "label-button": ["Hanken Grotesk", "sans-serif"],
        "label-technical": ["JetBrains Mono", "monospace"],
        "body-md": ["Source Serif 4", "serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Source Serif 4", "serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        // headline-lg-mobile: 40px from homepage (mobile nav used site-wide)
        "headline-lg-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        // display-xl-mobile: 64px — used for case-study stat numbers (short strings, fit fine at 64px)
        "display-xl-mobile": ["64px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "800" }],
        // display-lg-mobile: fluid 44px-64px — homepage hero H1 and final-CTA H2. Words like "MARKETING"
        // and "RETENTION" overflow narrow phones at a flat 64px, so this scales down only on screens where
        // it would actually overflow (~<390px wide) and stays full-size (64px) on larger phones.
        "display-lg-mobile": ["clamp(2.75rem, 19vw - 0.875rem, 4rem)", { lineHeight: "1", letterSpacing: "-0.02em", fontWeight: "800" }],
        // display-xl: desktop hero on homepage
        "display-xl": ["120px", { lineHeight: "110px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "label-button": ["14px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-technical": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        // headline-lg: 56px (most pages); homepage sections slightly smaller than before (was 64px)
        "headline-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
