import {
  Code2,
  Palette,
  Zap,
  Shield,
  Smartphone,
  Layout,
  Pen,
  TrendingUp,
  Lightbulb,
  Layers,
  Truck,
  Heart,
  Settings,
  Bell,
  Briefcase,
  Camera,
  DownloadCloud,
  Eye,
  Gauge,
  Gift,
  Globe,
  Headphones,
  Home,
  Image,
  Inbox,
  Lock,
  Mail,
  Package,
  RefreshCw,
  Search,
  Send,
  Smile,
  Star,
  Target,
  Terminal,
  Trash2,
  Unlock,
  Video,
  Volume2,
  Wifi,
  X,
  Zap as Zap2,
  BarChart3,
  Database,
  Folder,
  GitBranch,
  Cpu,
  Rocket,
  Crosshair,
  RotateCcw,
  Bookmark,
  MapPin,
  MessageSquare,
  Phone,
  Share2,
  User,
  CheckCircle,
  AlertCircle,
  HelpCircle,
  ChevronRight,
} from "lucide-react";

export type IconName = keyof typeof ICON_LIST;

export const ICON_LIST = {
  code: { name: "Code", icon: Code2 },
  palette: { name: "Palette", icon: Palette },
  zap: { name: "Zap", icon: Zap },
  shield: { name: "Shield", icon: Shield },
  smartphone: { name: "Smartphone", icon: Smartphone },
  layout: { name: "Layout", icon: Layout },
  pen: { name: "Pen", icon: Pen },
  trending: { name: "Trending Up", icon: TrendingUp },
  lightbulb: { name: "Lightbulb", icon: Lightbulb },
  layers: { name: "Layers", icon: Layers },
  truck: { name: "Truck", icon: Truck },
  heart: { name: "Heart", icon: Heart },
  settings: { name: "Settings", icon: Settings },
  bell: { name: "Bell", icon: Bell },
  briefcase: { name: "Briefcase", icon: Briefcase },
  camera: { name: "Camera", icon: Camera },
  download: { name: "Download", icon: DownloadCloud },
  eye: { name: "Eye", icon: Eye },
  gauge: { name: "Gauge", icon: Gauge },
  gift: { name: "Gift", icon: Gift },
  globe: { name: "Globe", icon: Globe },
  headphones: { name: "Headphones", icon: Headphones },
  home: { name: "Home", icon: Home },
  image: { name: "Image", icon: Image },
  inbox: { name: "Inbox", icon: Inbox },
  lock: { name: "Lock", icon: Lock },
  mail: { name: "Mail", icon: Mail },
  package: { name: "Package", icon: Package },
  refresh: { name: "Refresh", icon: RefreshCw },
  search: { name: "Search", icon: Search },
  send: { name: "Send", icon: Send },
  smile: { name: "Smile", icon: Smile },
  star: { name: "Star", icon: Star },
  target: { name: "Target", icon: Target },
  terminal: { name: "Terminal", icon: Terminal },
  trash: { name: "Trash", icon: Trash2 },
  unlock: { name: "Unlock", icon: Unlock },
  video: { name: "Video", icon: Video },
  volume: { name: "Volume", icon: Volume2 },
  wifi: { name: "Wifi", icon: Wifi },
  bar: { name: "Bar Chart", icon: BarChart3 },
  database: { name: "Database", icon: Database },
  folder: { name: "Folder", icon: Folder },
  git: { name: "Git", icon: GitBranch },
  cpu: { name: "Cpu", icon: Cpu },
  rocket: { name: "Rocket", icon: Rocket },
  crosshair: { name: "Crosshair", icon: Crosshair },
  rotate: { name: "Rotate", icon: RotateCcw },
  bookmark: { name: "Bookmark", icon: Bookmark },
  mappin: { name: "Map Pin", icon: MapPin },
  message: { name: "Message", icon: MessageSquare },
  phone: { name: "Phone", icon: Phone },
  share: { name: "Share", icon: Share2 },
  user: { name: "User", icon: User },
  check: { name: "Check Circle", icon: CheckCircle },
  alert: { name: "Alert Circle", icon: AlertCircle },
  help: { name: "Help Circle", icon: HelpCircle },
  chevron: { name: "Chevron Right", icon: ChevronRight },
} as const;

export const ICON_OPTIONS = Object.entries(ICON_LIST).map(([key, { name }]) => ({
  value: key,
  label: name,
}));

export function getIcon(iconName: string): React.ComponentType<any> | null {
  const icon = ICON_LIST[iconName as IconName];
  return icon ? icon.icon : null;
}
